server {
    listen 80;
    server_name taskflow.massinissaamir.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taskflow.massinissaamir.dev;

    ssl_certificate /etc/letsencrypt/live/taskflow.massinissaamir.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taskflow.massinissaamir.dev/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /actuator/ {
        proxy_pass http://backend:8080;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}