spring:
  application:
    name: taskflow-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: ${DB_USER:taskflow_user}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: ignored

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info